/** Remote sprite URLs (PokéAPI GitHub mirror). No local assets required. */
import FORM_SPRITES from './formSprites.json';

const SPRITE_BASE = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon';

export type PokemonSpriteVariant = 'default' | 'artwork' | 'shiny';

// Alternate forms share their base species' dex (all six Rotom are #0479), so a
// dex-only URL renders the base sprite for every form. PokeAPI gives each form
// its own numeric sprite id; formSprites.json (generated by
// scripts/fetch-form-sprites.mjs) maps a normalized species name to it. Keep
// this normalizer in sync with normName() in that script.
const formSprites: Record<string, number> = FORM_SPRITES;
function normName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[’']/g, '')
    .replace(/\./g, '')
    .replace(/:/g, '')
    .replace(/é/g, 'e')
    .replace(/%/g, '')
    .replace(/\s+/g, '-');
}

export function pokemonSpriteUrl(
  dex: number,
  variant: PokemonSpriteVariant = 'default',
  name?: string,
): string | null {
  // Prefer a form-specific sprite id when the name resolves to one; otherwise
  // fall back to the dex number (correct for base species and undistinguished
  // cosmetic forms).
  const formId = name ? formSprites[normName(name)] : undefined;
  if (formId == null && (!Number.isFinite(dex) || dex < 1)) return null;
  const id = formId ?? Math.floor(dex);
  if (variant === 'artwork') {
    return `${SPRITE_BASE}/other/official-artwork/${id}.png`;
  }
  if (variant === 'shiny') {
    return `${SPRITE_BASE}/shiny/${id}.png`;
  }
  return `${SPRITE_BASE}/${id}.png`;
}

export function dexForSpeciesName(pokemon: { id: string; name: string; dex: number }[], name: string): number | null {
  const q = name.trim().toLowerCase();
  if (!q) return null;
  const hit =
    pokemon.find((p) => p.name.toLowerCase() === q) ??
    pokemon.find((p) => p.id.toLowerCase() === q.replace(/\s+/g, '-'));
  return hit && hit.dex > 0 ? hit.dex : null;
}
